// Common disposable/temporary email domains
const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com", "guerrillamail.com", "guerrillamail.net", "tempmail.com",
  "throwaway.email", "temp-mail.org", "fakeinbox.com", "sharklasers.com",
  "guerrillamailblock.com", "grr.la", "yopmail.com", "yopmail.fr",
  "trashmail.com", "trashmail.me", "trashmail.net", "10minutemail.com",
  "10minutemail.net", "minutemail.com", "tempail.com", "tempr.email",
  "discard.email", "discardmail.com", "mailnesia.com", "maildrop.cc",
  "mailcatch.com", "mailexpire.com", "meltmail.com", "mintemail.com",
  "mohmal.com", "mytemp.email", "nada.email", "nomail.xl.cx",
  "spam4.me", "spamfree24.org", "tempmailaddress.com", "tempsky.com",
  "throwam.com", "tmpmail.net", "tmpmail.org", "trash-me.com",
  "wegwerfemail.de", "emailondeck.com", "getnada.com", "inboxbear.com",
  "mailsac.com", "burnermail.io", "harakirimail.com", "crazymailing.com",
  "dispostable.com", "getairmail.com", "jetable.org", "mailforspam.com",
  "mailhazard.com", "mailme24.com", "mailmoat.com", "mailshell.com",
  "mailtemp.info", "mailzilla.com", "nowmymail.com", "spamgourmet.com",
  "tempomail.fr", "thankyou2010.com", "trashemail.de", "trbvm.com",
  "trbvn.com", "uggsrock.com", "mailinator.net", "spambox.us",
  "disbox.net", "disbox.org", "disposableemailaddresses.emailmiser.com",
  "emailigo.de", "emailmiser.com", "emailsensei.com", "emailtemporario.com.br",
  "ephemail.net", "filzmail.com", "fixmail.tk", "flurred.com",
  "fr33mail.info", "frapmail.com", "gishpuppy.com", "great-host.in",
  "greensloth.com", "haltospam.com", "incognitomail.org", "imails.info",
  "instant-mail.de", "ipoo.org", "irish2me.com", "jetable.com",
  "kasmail.com", "koszmail.pl", "kurzepost.de", "lifebyfood.com",
  "lookugly.com", "lr78.com", "maileater.com", "mailexpire.com",
  "mailfreeonline.com", "mailguard.me", "mailimate.com", "mailismagic.com",
  "mailnull.com", "mailquack.com", "mailscrap.com", "mailseal.de",
  "mailsiphon.com", "mailslite.com", "mailzilla.org", "mbx.cc",
  "mega.zik.dj", "meinspamschutz.de", "mmmmail.com", "mobi.web.id",
  "mt2015.com", "mytrashmail.com", "nobulk.com", "noclickemail.com",
  "nogmailspam.info", "nomail.pw", "nomail.xl.cx", "nomorespamemails.com",
  "nospam.ze.tc", "nospam4.us", "notmailinator.com", "nowmymail.com",
  "objectmail.com", "obobbo.com", "odaymail.com", "onewaymail.com",
  "otherinbox.com", "ourklips.com", "outlawspam.com", "ovpn.to",
  "owlpic.com", "pancakemail.com", "proxymail.eu", "punkass.com",
  "putthisinyouremail.com", "reallymymail.com", "recode.me",
  "regbypass.com", "rmqkr.net", "s0ny.net", "safe-mail.net",
  "safersignup.de", "safetymail.info", "sandelf.de", "saynotospams.com",
  "scatmail.com", "schafmail.de", "selfdestructingmail.com", "sendspamhere.com",
  "shieldedmail.com", "shiftmail.com", "skeefmail.com", "slaskpost.se",
  "slipry.net", "slopsbox.com", "smashmail.de", "soodonims.com",
  "spam.la", "spam.su", "spamavert.com", "spambob.com", "spambob.net",
  "spambob.org", "spambog.com", "spambog.de", "spambog.ru",
  "spamcannon.com", "spamcannon.net", "spamcero.com", "spamcon.org",
  "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net", "spamcowboy.org",
  "spamday.com", "spamex.com", "spamfighter.cf", "spamfighter.ga",
  "spamfighter.gq", "spamfighter.ml", "spamfighter.tk", "spamfree.eu",
  "spamfree24.com", "spamfree24.de", "spamfree24.eu", "spamfree24.info",
  "spamfree24.net", "spamgoes.in", "spamherelots.com", "spamhereplease.com",
  "spamhole.com", "spamify.com", "spaminator.de", "spamkill.info",
  "spaml.com", "spaml.de", "spammotel.com", "spamobox.com",
  "spamoff.de", "spamslicer.com", "spamspot.com", "spamstack.net",
  "spamthis.co.uk", "spamthisplease.com", "spamtrail.com", "spamtrap.ro",
  "speed.1s.fr", "supergreatmail.com", "supermailer.jp", "superrito.com",
  "superstachel.de", "suremail.info", "teleworm.com", "teleworm.us",
  "tempalias.com", "tempe4mail.com", "tempemail.biz", "tempemail.co.za",
  "tempemail.com", "tempemail.net", "tempinbox.com", "tempinbox.co.uk",
  "tempmail.eu", "tempmail.it", "tempmail2.com", "tempmaildemo.com",
  "tempmailer.com", "tempmailer.de", "tempomail.fr", "temporarily.de",
  "temporarioemail.com.br", "temporaryemail.net", "temporaryemail.us",
  "temporaryforwarding.com", "temporaryinbox.com", "temporarymailaddress.com",
  "thanksnospam.info", "thankyou2010.com", "thisisnotmyrealemail.com",
  "throwawayemailaddress.com", "tittbit.in", "tizi.com", "tmailinator.com",
  "toiea.com", "tradermail.info", "trash2009.com", "trash2010.com",
  "trash2011.com", "trashdevil.com", "trashdevil.de", "trashmail.at",
  "trashmail.de", "trashmail.io", "trashmail.org", "trashmail.ws",
  "trashmailer.com", "trashymail.com", "trashymail.net",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return true;
  return DISPOSABLE_DOMAINS.has(domain);
}
